# Generated by Django 5.2.11 on 2026-02-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoInhabilitacion',
            fields=[
                ('cod_motivo_inhabilitacion', models.AutoField(db_column='codMotivoInhabilitacion', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100, unique=True)),
                ('observacion', models.CharField(blank=True, db_column='observacion', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Motivo de Inhabilitación',
                'verbose_name_plural': 'Motivos de Inhabilitación',
                'db_table': 'MotivosInhabilitacion',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('cod_parentesco', models.AutoField(db_column='codParentesco', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
            ],
            options={
                'verbose_name': 'Parentesco',
                'verbose_name_plural': 'Parentescos',
                'db_table': 'Parentescos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoBeneficio',
            fields=[
                ('cod_tipo_beneficio', models.AutoField(db_column='codTipoBeneficio', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100, unique=True)),
                ('edad_minima', models.IntegerField(blank=True, db_column='edadMinima', null=True)),
                ('edad_maxima', models.IntegerField(blank=True, db_column='edadMaxima', null=True)),
                ('prioridad', models.IntegerField(db_column='prioridad')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
                ('observaciones', models.CharField(blank=True, db_column='observaciones', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Beneficio',
                'verbose_name_plural': 'Tipos de Beneficio',
                'db_table': 'TiposBeneficio',
                'ordering': ['prioridad', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('cod_beneficiario', models.AutoField(db_column='codBeneficiario', primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
                ('persona', models.ForeignKey(db_column='codPersona', on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='personas.persona')),
                ('socio', models.ForeignKey(db_column='codSocio', on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='personas.socio')),
                ('parentesco', models.ForeignKey(db_column='codParentesco', on_delete=django.db.models.deletion.PROTECT, related_name='beneficiarios', to='beneficiarios.parentesco')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'db_table': 'Beneficiarios',
                'ordering': ['persona'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoBeneficiario',
            fields=[
                ('cod_historico_beneficiario', models.AutoField(db_column='codHistoricoBeneficiario', primary_key=True, serialize=False)),
                ('peso', models.DecimalField(blank=True, db_column='peso', decimal_places=3, max_digits=9, null=True)),
                ('talla', models.DecimalField(blank=True, db_column='talla', decimal_places=2, max_digits=9, null=True)),
                ('hmg', models.DecimalField(blank=True, db_column='hmg', decimal_places=2, max_digits=9, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, db_column='fechaInicio')),
                ('fecha_termino', models.DateTimeField(blank=True, db_column='fechaTermino', null=True)),
                ('beneficiario', models.ForeignKey(db_column='codBeneficiario', on_delete=django.db.models.deletion.PROTECT, related_name='historicos', to='beneficiarios.beneficiario')),
                ('estado', models.ForeignKey(db_column='codEstado', on_delete=django.db.models.deletion.PROTECT, related_name='historicos_beneficiario', to='core.estado')),
                ('motivo_inhabilitacion', models.ForeignKey(blank=True, db_column='codMotivoInhabilitacion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historicos', to='beneficiarios.motivoinhabilitacion')),
                ('tipo_beneficio', models.ForeignKey(db_column='codTipoBeneficio', on_delete=django.db.models.deletion.PROTECT, related_name='historicos', to='beneficiarios.tipobeneficio')),
            ],
            options={
                'verbose_name': 'Histórico de Beneficiario',
                'verbose_name_plural': 'Históricos de Beneficiarios',
                'db_table': 'HistoricoBeneficiarios',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DatosObstetricos',
            fields=[
                ('cod_dato_obstetrico', models.AutoField(db_column='codDatoObstetrico', primary_key=True, serialize=False)),
                ('fecha_ultima_menstruacion', models.DateField(blank=True, db_column='fechaUltimaMestruacion', null=True)),
                ('fecha_probable_parto', models.DateField(blank=True, db_column='fechaProbableParto', null=True)),
                ('fecha_de_parto', models.DateField(blank=True, db_column='fechaDeParto', null=True)),
                ('fecha_fin_lactancia', models.DateField(blank=True, db_column='fechaFinLactancia', null=True)),
                ('historico', models.OneToOneField(db_column='codHistoricoBeneficiario', on_delete=django.db.models.deletion.CASCADE, related_name='datos_obstetricos', to='beneficiarios.historicobeneficiario')),
            ],
            options={
                'verbose_name': 'Dato Obstétrico',
                'verbose_name_plural': 'Datos Obstétricos',
                'db_table': 'DatosObstetricos',
            },
        ),
    ]
