# Generated by Django 5.2.11 on 2026-02-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociaciones', '0002_initial'),
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pecosa',
            fields=[
                ('cod_pecosa', models.AutoField(db_column='codPecosa', primary_key=True, serialize=False)),
                ('numero_pecosa', models.CharField(blank=True, db_column='numeroPecosa', max_length=8, null=True)),
                ('fecha_reparto', models.DateTimeField(blank=True, db_column='fechaReparto', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
                ('observacion', models.CharField(blank=True, db_column='observacion', max_length=255, null=True)),
                ('asociacion', models.ForeignKey(db_column='codAsociacion', on_delete=django.db.models.deletion.PROTECT, related_name='pecosas', to='asociaciones.asociacion')),
                ('estado', models.ForeignKey(db_column='codEstado', on_delete=django.db.models.deletion.PROTECT, related_name='pecosas', to='core.estado')),
                ('socio_presidenta', models.ForeignKey(db_column='codSocioPresidenta', on_delete=django.db.models.deletion.PROTECT, related_name='pecosas_como_presidenta', to='personas.socio')),
            ],
            options={
                'verbose_name': 'PECOSA',
                'verbose_name_plural': 'PECOSAS',
                'db_table': 'Pecosas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DetallePecosa',
            fields=[
                ('cod_detalle_pecosa', models.AutoField(db_column='codDetallePecosa', primary_key=True, serialize=False)),
                ('prioridad', models.IntegerField(db_column='prioridad')),
                ('fecha_desde', models.DateTimeField(blank=True, db_column='fechaDesde', null=True)),
                ('fecha_hasta', models.DateTimeField(blank=True, db_column='fechaHasta', null=True)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
                ('precio_unitario', models.DecimalField(db_column='precioUnitario', decimal_places=2, max_digits=9)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
                ('producto', models.ForeignKey(db_column='codProducto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pecosa', to='inventario.producto')),
                ('pecosa', models.ForeignKey(db_column='codPecosa', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='distribucion.pecosa')),
            ],
            options={
                'verbose_name': 'Detalle de PECOSA',
                'verbose_name_plural': 'Detalles de PECOSA',
                'db_table': 'DetallePecosa',
                'ordering': ['prioridad'],
            },
        ),
    ]
