# Generated by Django 5.2.11 on 2026-02-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('cod_estado', models.AutoField(db_column='codEstado', primary_key=True, serialize=False)),
                ('abreviatura', models.CharField(db_column='abreviatura', max_length=3, unique=True)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'Estados',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('cod_rol', models.AutoField(db_column='codRol', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
                'ordering': ['descripcion'],
            },
        ),
    ]
