# Generated by Django 5.2.11 on 2026-02-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociaciones', '0001_initial'),
        ('core', '0001_initial'),
        ('geografico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cod_persona', models.AutoField(db_column='codPersona', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='nombres', max_length=100)),
                ('apellido_paterno', models.CharField(db_column='apellidoPaterno', max_length=50)),
                ('apellido_materno', models.CharField(db_column='apellidoMaterno', max_length=50)),
                ('dni', models.CharField(db_column='dni', max_length=8, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], db_column='sexo', max_length=1)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=6, null=True)),
                ('celular', models.CharField(blank=True, db_column='celular', max_length=9, null=True)),
                ('fecha_nacimiento', models.DateField(db_column='fechaNacimiento')),
                ('direccion', models.CharField(db_column='direccion', max_length=100)),
                ('numero_finca', models.IntegerField(blank=True, db_column='numeroFinca', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
                ('sector_zona', models.ForeignKey(db_column='codSectorZona', on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='geografico.sectorzona')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'Personas',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('cod_socio', models.AutoField(db_column='codSocio', primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, db_column='fechaInicio')),
                ('fecha_fin', models.DateTimeField(blank=True, db_column='fechaFin', null=True)),
                ('observaciones', models.CharField(blank=True, db_column='observaciones', max_length=255, null=True)),
                ('asociacion', models.ForeignKey(db_column='codAsociacion', on_delete=django.db.models.deletion.PROTECT, related_name='socios', to='asociaciones.asociacion')),
                ('estado', models.ForeignKey(db_column='codEstado', on_delete=django.db.models.deletion.PROTECT, related_name='socios', to='core.estado')),
                ('persona', models.ForeignKey(db_column='codPersona', on_delete=django.db.models.deletion.PROTECT, related_name='socios', to='personas.persona')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'Socios',
                'ordering': ['persona'],
            },
        ),
    ]
