# Generated by Django 5.2.11 on 2026-02-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('geografico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cod_cargo', models.AutoField(db_column='codCargo', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'Cargos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('cod_reconocimiento', models.AutoField(db_column='codReconocimiento', primary_key=True, serialize=False)),
                ('documento', models.CharField(db_column='documento', max_length=100)),
                ('fecha_documento', models.DateTimeField(auto_now_add=True, db_column='fechaDocumento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
                ('fecha_inicio', models.DateField(db_column='fechaInicio')),
                ('fecha_fin', models.DateField(db_column='fechaFin')),
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
                'db_table': 'Reconocimientos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TipoLocal',
            fields=[
                ('cod_tipo_local', models.AutoField(db_column='codTipoLocal', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
            ],
            options={
                'verbose_name': 'Tipo de Local',
                'verbose_name_plural': 'Tipos de Local',
                'db_table': 'TiposLocal',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Asociacion',
            fields=[
                ('cod_asociacion', models.AutoField(db_column='codAsociacion', primary_key=True, serialize=False)),
                ('codigo_asociacion', models.CharField(db_column='codigoAsociacion', max_length=20, unique=True)),
                ('nombre_asociacion', models.CharField(blank=True, db_column='nombreAsociacion', max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(db_column='direccion', max_length=200)),
                ('numero_finca', models.IntegerField(blank=True, db_column='numeroFinca', null=True)),
                ('observaciones', models.CharField(blank=True, db_column='observaciones', max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
                ('estado', models.ForeignKey(db_column='codEstado', on_delete=django.db.models.deletion.PROTECT, related_name='asociaciones', to='core.estado')),
                ('sector_zona', models.ForeignKey(db_column='codSectorZona', on_delete=django.db.models.deletion.PROTECT, related_name='asociaciones', to='geografico.sectorzona')),
            ],
            options={
                'verbose_name': 'Asociación',
                'verbose_name_plural': 'Asociaciones',
                'db_table': 'Asociaciones',
                'ordering': ['nombre_asociacion'],
            },
        ),
        migrations.CreateModel(
            name='Directiva',
            fields=[
                ('cod_directiva', models.AutoField(db_column='codDirectiva', primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
                ('cargo', models.ForeignKey(db_column='codCargo', on_delete=django.db.models.deletion.PROTECT, related_name='directivas', to='asociaciones.cargo')),
                ('estado', models.ForeignKey(db_column='codEstado', on_delete=django.db.models.deletion.PROTECT, related_name='directivas', to='core.estado')),
            ],
            options={
                'verbose_name': 'Directiva',
                'verbose_name_plural': 'Directivas',
                'db_table': 'Directivas',
                'ordering': ['reconocimiento', 'cargo'],
            },
        ),
    ]
