# Generated by Django 5.2.11 on 2026-02-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociaciones', '0001_initial'),
        ('core', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directiva',
            name='socio',
            field=models.ForeignKey(db_column='codSocio', on_delete=django.db.models.deletion.PROTECT, related_name='directivas', to='personas.socio'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='asociacion',
            field=models.ForeignKey(db_column='codAsociacion', on_delete=django.db.models.deletion.PROTECT, related_name='reconocimientos', to='asociaciones.asociacion'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='estado',
            field=models.ForeignKey(db_column='codEstado', on_delete=django.db.models.deletion.PROTECT, related_name='reconocimientos', to='core.estado'),
        ),
        migrations.AddField(
            model_name='directiva',
            name='reconocimiento',
            field=models.ForeignKey(db_column='codReconocimiento', on_delete=django.db.models.deletion.PROTECT, related_name='directivas', to='asociaciones.reconocimiento'),
        ),
        migrations.AddField(
            model_name='asociacion',
            name='tipo_local',
            field=models.ForeignKey(db_column='codTipoLocal', on_delete=django.db.models.deletion.PROTECT, related_name='asociaciones', to='asociaciones.tipolocal'),
        ),
    ]
