# Generated by Django 5.2.11 on 2026-02-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('cod_tipo_movimiento', models.AutoField(db_column='codTipoMovimiento', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos de Movimiento',
                'db_table': 'TipoMovimiento',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('cod_unidad_medida', models.AutoField(db_column='codUnidadMedida', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'UnidadMedida',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.AutoField(db_column='codProducto', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100, unique=True)),
                ('abreviatura', models.CharField(blank=True, db_column='abreviatura', max_length=5, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
                ('stock', models.IntegerField(blank=True, db_column='stock', null=True)),
                ('precio_unitario', models.DecimalField(blank=True, db_column='precioUnitario', decimal_places=2, max_digits=9, null=True)),
                ('estado', models.ForeignKey(db_column='codEstado', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.estado')),
                ('unidad_medida', models.ForeignKey(db_column='codUnidadMedida', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.unidadmedida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Productos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('cod_movimiento', models.AutoField(db_column='codMovimiento', primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, db_column='fechaMovimiento')),
                ('cantidad', models.IntegerField(db_column='cantidad')),
                ('precio_unitario', models.DecimalField(db_column='precioUnitario', decimal_places=2, max_digits=9)),
                ('precio_total', models.DecimalField(db_column='precioTotal', decimal_places=2, max_digits=9)),
                ('producto', models.ForeignKey(db_column='codProducto', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto')),
                ('tipo_movimiento', models.ForeignKey(db_column='codTipoMovimiento', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.tipomovimiento')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'Movimientos',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
