# Generated by Django 5.2.11 on 2026-02-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('cod_sector', models.AutoField(db_column='codSector', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=100, null=True, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'db_table': 'Sectores',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('cod_zona', models.AutoField(db_column='codZona', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=100, null=True, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'Zonas',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='SectorZona',
            fields=[
                ('cod_sector_zona', models.AutoField(db_column='codSectorZona', primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro')),
                ('sector', models.ForeignKey(db_column='fkCodSector', on_delete=django.db.models.deletion.PROTECT, related_name='zonas_sector', to='geografico.sector')),
                ('zona', models.ForeignKey(db_column='codZona', on_delete=django.db.models.deletion.PROTECT, related_name='sectores_zona', to='geografico.zona')),
            ],
            options={
                'verbose_name': 'Sector-Zona',
                'verbose_name_plural': 'Sectores-Zona',
                'db_table': 'SectoresZona',
                'ordering': ['zona', 'sector'],
                'unique_together': {('zona', 'sector')},
            },
        ),
    ]
